name: Integration
on: [push]
jobs:
  tests-on:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build Dockerfile
      run: docker build .
